# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jacob/Xilinx/Vivado/2023.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/pynq-z2/A.0/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/led_blink/led_blink.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blink || ORIG_REF_NAME==led_blink} -quiet] -quiet

# XDC: /home/jacob/Documents/Semester4/FPGA/Vivado/Lab4/Lab4.gen/sources_1/bd/led_blink/led_blink_ooc.xdc
